language: node_js
node_js: 0.11
install:
  - gem install mdl
  - npm install -g markdownlint-cli

  # Obtain development version of remark
  - git clone --depth 1 https://github.com/wooorm/remark $HOME/remark
  - cd $HOME/remark
  - git show --oneline -s
  - npm install lerna
  - npm install --production
  - npm install remark-validate-links remark-lint
  - cd -
script:
  - mdl -c ./.mdlrc README.md
  - markdownlint -c ./.markdownlint.json README.md
  - node $HOME/remark/packages/remark-cli/cli.js --config=./.remarkrc.js --frail --no-stdout -u remark-lint README.md
  # Do not fail on the invalid links from issue #3
  - node $HOME/remark/packages/remark-cli/cli.js --no-stdout -u remark-validate-links README.md
